name: handwritio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.1.2
  path: ^1.9.1
  mime: ^2.0.0

dev_dependencies:
  flutter_launcher_icons : "^0.9.2"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg  # For background.jpeg

flutter_icons:
  android: "assets/AND_Icon_Handwritio.ai"
  ios: "assets/IOS_Icon_Handwritio.ai"
  web: "assets/IOS_Icon_Handwritio.ai"
